export const dummyUsers = [
    {
        clerkId: "clerkId1",
        imageUrl: "https://picsum.photos/id/237/200/300",
        email: "example@example.com",
        website: "enyaumanzor.com",
        username: "enyaumanzor",
        firstName: "Enya",
        lastName: "Umanzor",
        location: "24 whitecres Ave, Calgary AB",
        contactNumber: "587 946 5893",
        serviceIDs: ["1", "2"],
        reviewIDs: ["1", "2"],
    },
    {
        clerkId: "clerkId2",
        imageUrl: "https://picsum.photos/id/237/200/300",
        email: "example2@example.com",
        website: "enyaumanzor.com",
        username: "cacofelix",
        firstName: "Felix",
        lastName: "Catton",
        location: "Your mama's house",
        contactNumber: "587 946 5892",
        serviceIDs: [],
        reviewIDs: [],
    },
    {
        clerkId: "clerkId3",
        imageUrl: "http://example.com/profile",
        email: "example3@example.com",
        website: "enyaumanzor.com",
        username: "username3",
        firstName: "FirstName3",
        lastName: "LastName3",
        location: "Location3",
        contactNumber: "587 946 1111",
        serviceIDs: [],
        reviewIDs: [],
    },
];

export default dummyUsers;
