import { DummyUser } from '@/types';

export const dummyUsers: any[] = [

    // Home
    // ASAP Plumbers
    {
        // _id: "65fe9a5396346912b7163240",
        clerkId: "clerkId1",
        imageUrl: "https://source.unsplash.com/man-in-orange-and-white-striped-crew-neck-shirt-UpjtG9zkqdc",
        email: "jack@plumbingforyou.com",
        website: "plumbingforyou.com",
        username: "jackplumber",
        firstName: "Jack",
        lastName: "Plumber",
        location: "New York, NY",
        contactNumber: "333-456-7890",
        serviceIDs: ["1"],
        reviewIDs: [],
        reservationIDs: ["1", "2", "3"],
    },
    // Soph Cleaning
    {
        // _id: "65fe9a5396346912b7163242",
        clerkId: "clerkId2",
        imageUrl: "https://source.unsplash.com/smiling-woman-sitting-in-vehicle-OH3AKVadoxE",
        email: "sophia@cleaningforyou.com",
        website: "cleaningforyou.com",
        username: "sophcleaner",
        firstName: "Sophia",
        lastName: "Cleaner",
        location: "Chicago, IL",
        contactNumber: "345-678-9012",
        serviceIDs: ["2"],
        reviewIDs: [],
        reservationIDs: ["4", "5", "6"],
    },
    // Noah Lawns
    {
        // _id: "65fe9a5396346912b7163243",
        clerkId: "clerkId3",
        imageUrl: "https://source.unsplash.com/man-in-white-crew-neck-t-shirt-with-tattoo-on-arm-nMv8DMdM4Z8",
        email: "noah@lawnforyou.com",
        website: "lawnforyou.com",
        username: "noahlawn",
        firstName: "Noah",
        lastName: "Lawn",
        location: "Houston, TX",
        contactNumber: "456-789-0123",
        serviceIDs: ["3"],
        reviewIDs: [],
        reservationIDs: ["7", "8", "9"],
    },
    // Home Security System
    {
        // _id: "65fe9a5396346912b7163244",
        clerkId: "clerkId4",
        imageUrl: "https://source.unsplash.com/smiling-woman-in-white-tank-top-mx-ukEhDpHo",
        contactNumber: "567-890-1434",
        email: "olivia@securityforyou.com",
        website: "securityforyou.com",
        username: "oliviasecurity",
        firstName: "Olivia",
        lastName: "Security",
        location: "Seattle, WA",
        serviceIDs: ["4"],
        reviewIDs: [],
        reservationIDs: ["10", "11", "12"],
    },
    // Home Organizer
    {
        // _id: "65fe9a5396346912b7163245",
        clerkId: "clerkId5",
        imageUrl: "https://source.unsplash.com/man-taking-selfie-tidSLv-UaNs",
        contactNumber: "678-901-2345",
        email: "liam@organizingforyou.com",
        website: "organizingforyou.com",
        username: "liamorganizer",
        firstName: "Liam",
        lastName: "Organizer",
        location: "San Francisco, CA",
        serviceIDs: ["5"],
        reviewIDs: [],
        reservationIDs: ["13", "14", "15"],
    },

    // Personal
    // Personal Trainer
    {
        // _id: "65fe9a5396346912b7163255",
        clerkId: "clerkId6",
        imageUrl: "https://source.unsplash.com/man-in-blue-crew-neck-shirt-4uj3iZ5m084",
        contactNumber: "123-789-4560",
        email: "max@fitforyou.com",
        website: "fitforyou.com",
        username: "maxfit",
        firstName: "Max",
        lastName: "Fit",
        location: "Miami, FL",
        serviceIDs: ["6"],
        reviewIDs: [],
        reservationIDs: ["16", "17", "18"],
    },
    // Yoga Instructor
    {
        // _id: "65fe9a5396346912b7163250",
        clerkId: "clerkId7",
        imageUrl: "https://source.unsplash.com/a-woman-holding-a-piece-of-luggage-o2hPCfwPPkw",
        contactNumber: "456-789-1230",
        email: "ava@yogaforyou.com",
        website: "yogaforyou.com",
        username: "avayogi",
        firstName: "Ava",
        lastName: "Yogi",
        location: "Los Angeles, CA",
        serviceIDs: ["7"],
        reviewIDs: [],
        reservationIDs: ["19", "20", "21"],
    },
    // Personal Nutritionist
    {
        // _id: "65fe9a5396346912c7163257",
        clerkId: "clerkId8",
        imageUrl: "https://source.unsplash.com/woman-in-black-long-sleeve-shirt-sitting-on-white-couch-n1B6ftPB5Eg",
        contactNumber: "789-123-4560",
        email: "emma@nutritionforyou.com",
        website: "nutritionforyou.com",
        username: "emmanutri",
        firstName: "Emma",
        lastName: "Nutri",
        location: "New York, NY",
        serviceIDs: ["8"],
        reviewIDs: [],
        reservationIDs: ["22", "23", "24"],
    },
    // Life Coach
    {
        // _id: "65fe9a5396346912b7133258",
        clerkId: "clerkId9",
        imageUrl: "https://source.unsplash.com/woman-with-red-lipstick-and-black-mascara-7tz7I7naQ8c",
        contactNumber: "534-567-8901",
        email: "ethan@lifecoaching.com",
        website: "lifecoaching.com",
        username: "ethancoach",
        firstName: "Ethan",
        lastName: "Coach",
        location: "Chicago, IL",
        serviceIDs: ["9"],
        reviewIDs: [],
        reservationIDs: ["25", "26", "27"],
    },
    // Beauty Consultant
    {
        // _id: "65fe9z5396346912b7163259",
        clerkId: "clerkId10",
        imageUrl: "https://source.unsplash.com/woman-doing-her-makeup-eN34gxd3-1w",
        contactNumber: "345-678-9013",
        email: "olivia@beautyforyou.com",
        website: "beautyforyou.com",
        username: "oliviabeauty",
        firstName: "Olivia",
        lastName: "Beauty",
        location: "San Francisco, CA",
        serviceIDs: ["10"],
        reviewIDs: [],
        reservationIDs: ["28", "29", "30"],
    },
    // Finance Advisor
    {
        // _id: "65fe9a5396346912b7163260",
        clerkId: "clerkId11",
        imageUrl: "https://source.unsplash.com/man-wearing-black-and-teal-dress-suit-standing-near-gray-wall-h5cd51KXmRQ",
        contactNumber: "456-789-0124",
        email: "noah@financeforyou.com",
        website: "financeforyou.com",
        username: "noahfinance",
        firstName: "Noah",
        lastName: "Finance",
        location: "Houston, TX",
        serviceIDs: ["11"],
        reviewIDs: [],
        reservationIDs: ["31", "32", "33"],
    },

    // Tech
    // Emily Types
    {
        // _id: "65fe9a5396346912b7163290",
        clerkId: "clerkId12",
        imageUrl: "https://source.unsplash.com/woman-in-green-shirt-sitting-in-front-of-computer-64YrPKiguAE",
        contactNumber: "444-456-7890",
        email: "emily@editingforyou.com",
        website: "editingforyou.com",
        username: "emilyeditor",
        firstName: "Emily",
        lastName: "Editor",
        location: "New York, NY",
        serviceIDs: ["12"],
        reviewIDs: [],
        reservationIDs: ["34", "35", "36"],
    },
    // IT Support by David
    {
        // _id: "65fe9a5396346912b7163291",
        clerkId: "clerkId13",
        imageUrl: "https://source.unsplash.com/man-in-gray-button-up-shirt-EZ4TYgXPNWk",
        contactNumber: "239-567-8901",  
        email: "david@itsupportforyou.com",
        website: "itsupportforyou.com",
        username: "davidit",
        firstName: "David",
        lastName: "IT",
        location: "Los Angeles, CA",
        serviceIDs: ["13"],
        reviewIDs: [],
        reservationIDs: ["37", "38", "39"],
    },
    // Michael Developments
    {
        // _id: "65fe9a5396346912b7163292",
        clerkId: "clerkId14",
        imageUrl: "https://source.unsplash.com/a-man-in-blue-overalls-working-on-cement-nZZfP9QiQ6w",
        contactNumber: "345-678-9014",
        email: "michael@developmentforyou.com",
        website: "developmentforyou.com",
        username: "michaeldev",
        firstName: "Michael",
        lastName: "Developer",
        location: "Chicago, IL",
        serviceIDs: ["14"],
        reviewIDs: [],
        reservationIDs: ["40", "41", "42"],
    },
    // Ethan Cyber Consultancy
    {
        // _id: "65fe9a5396346912b7163294",
        clerkId: "clerkId15",
        imageUrl: "https://source.unsplash.com/man-wearing-headphones-while-sitting-on-chair-in-front-of-macbook-4-EeTnaC1S4",
        contactNumber: "567-890-1234",
        email: "ethan@cybersecurityforyou.com",
        website: "cybersecurityforyou.com",
        username: "ethancyber",
        firstName: "Ethan",
        lastName: "Cybersecurity",
        location: "Houston, TX",
        serviceIDs: ["15"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // Cloud Solutions and Aid
    {
        // _id: "65fe9a5396346912b7163295",
        clerkId: "clerkId16",
        imageUrl: "https://source.unsplash.com/smiling-man-using-laptop-computer-while-sitting-on-black-leather-sofa-LCcFI_26diA",
        contactNumber: "678-902-2345",
        email: "aiden@cloudsolutionsforyou.com",
        website: "cloudsolutionsforyou.com",
        username: "aidencloud",
        firstName: "Aiden",
        lastName: "Architect",
        location: "Boston, MA",
        serviceIDs: ["16"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // Analysis Freelance Soph
    {
        // _id: "65fe9a5396346912b7163293",
        clerkId: "clerkId17",
        imageUrl: "https://source.unsplash.com/shallow-focus-photo-of-woman-in-gray-jacket-0Zx1bDv5BNY",
        contactNumber: "456-789-0125",
        email: "sophia@dataanalysisforyou.com",
        website: "dataanalysisforyou.com",
        username: "sophiaanalyst",
        firstName: "Sophia",
        lastName: "Analyst",
        location: "San Diego, CA",
        serviceIDs: ["17"],
        reviewIDs: [],
        reservationIDs: [],
    },

    // Advisory
    // Liv Leagal
    {
        // _id: "65fe9a5396346912b7163296",
        clerkId: "clerkId18",
        imageUrl: "https://source.unsplash.com/five-person-by-table-watching-turned-on-white-imac-vbxyFxlgpjM",
        contactNumber: "789-012-3456",
        email: "olivia@legaladviceforyou.com",
        website: "legaladviceforyou.com",
        username: "olivialegal",
        firstName: "Olivia",
        lastName: "Legal",
        location: "Washington, DC",
        serviceIDs: ["18"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // Elijah Business
    {
        // _id: "65fe9a5396346912b7163297",
        clerkId: "clerkId19",
        imageUrl: "https://source.unsplash.com/man-sitting-on-chair-E9PFbdhZmus",
        contactNumber: "890-123-4567",
        email: "elijah@businessconsultingforyou.com",
        website: "businessconsultingforyou.com",
        username: "elijahbusiness",
        firstName: "Elijah",
        lastName: "Consultant",
        location: "San Francisco, CA",
        serviceIDs: ["19"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // Ava Fiscal
    {
        // _id: "65fe9a5396346912b7163298",
        clerkId: "clerkId20",
        imageUrl: "https://source.unsplash.com/a-person-holding-a-laptop-7mBictB_urk",
        contactNumber: "901-234-5678",
        email: "ava@financialadvisorforyou.com",
        website: "financialadvisorforyou.com",
        username: "avafiscal",
        firstName: "Ava",
        lastName: "Financial",
        location: "New York, NY",
        serviceIDs: ["20"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // Marketing by Liam
    {
        // _id: "65fe9a5396346912b7163299",
        clerkId: "clerkId21",
        imageUrl: "https://source.unsplash.com/a-man-talking-on-a-cell-phone-dxnEyQszbUo",
        contactNumber: "312-345-6789",
        email: "liam@marketingconsultingforyou.com",
        website: "marketingconsultingforyou.com",
        username: "liammarketing",
        firstName: "Liam",
        lastName: "Marketing",
        location: "Chicago, IL",
        serviceIDs: ["21"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // Mia's Advisory
    {
        // _id: "65fe9a5396346912b7163300",
        clerkId: "clerkId22",
        imageUrl: "https://source.unsplash.com/a-woman-and-a-girl-looking-at-a-laptop-coCGW4SsxX4",
        contactNumber: "345-678-9015",
        email: "mia@investmentadvisorforyou.com",
        website: "investmentadvisorforyou.com",
        username: "miainvestment",
        firstName: "Mia",
        lastName: "Investment",
        location: "Los Angeles, CA",
        serviceIDs: ["22"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // HR Consultancy 
    {
        // _id: "65fe9a5396346912b7163301",
        clerkId: "clerkId23",
        imageUrl: "https://source.unsplash.com/man-in-black-dress-shirt-K2sjNLfJpc4",
        contactNumber: "456-789-0135",
        email: "noah@hrconsultingforyou.com",
        website: "hrconsultingforyou.com",
        username: "noahhr",
        firstName: "Noah",
        lastName: "HR",
        location: "Seattle, WA",
        serviceIDs: ["23"],
        reviewIDs: [],
        reservationIDs: [],
    },

    // Creative
    // Fine Art Painting
    {
        // _id: "65fe9a5396346912b7163302",
        clerkId: "clerkId24",
        imageUrl: "https://source.unsplash.com/woman-in-white-and-black-striped-long-sleeve-shirt-and-blue-denim-jeans-sitting-on-bed-aYwJeBcFEQQ",
        contactNumber: "555-456-7890",
        email: "artist@example.com",
        website: "artistwebsite.com",
        username: "artist123",
        firstName: "Alice",
        lastName: "Artist",
        location: "New York, NY",
        serviceIDs: ["24"],
        reviewIDs: []
    },
    // Professional Photography
    {
        // _id: "65fe9a5396346912b7163303",
        clerkId: "clerkId25",
        imageUrl: "https://source.unsplash.com/man-looking-up-bQ0TogIULCM",
        contactNumber: "234-567-8901",
        email: "photographer@example.com",
        website: "photographerwebsite.com",
        username: "photographer321",
        firstName: "Bob",
        lastName: "Photographer",
        location: "Los Angeles, CA",
        serviceIDs: ["25"],
        reviewIDs: []
    },
    // Sculpture Art
    {
        // _id: "65fe9a5396346912b7163304",
        clerkId: "clerkId26",
        imageUrl: "https://source.unsplash.com/man-painting-ceramic-mug-mBbHdcpn3eM",
        contactNumber: "345-678-9017",
        email: "sculptor@example.com",
        website: "sculptorwebsite.com",
        username: "sculptor456",
        firstName: "Charlie",
        lastName: "Sculptor",
        location: "Chicago, IL",
        serviceIDs: ["26"],
        reviewIDs: []
    },
    // Nature Photography
    {
        // _id: "65fe9a5396346912b7163305",
        clerkId: "clerkId27",
        imageUrl: "https://source.unsplash.com/man-wearing-black-sweater-and-red-knitted-cap-D6MmPV6SHqg",
        contactNumber: "456-789-0139",
        email: "naturephotographer@example.com",
        website: "naturephotographerwebsite.com",
        username: "naturelover789",
        firstName: "Diana",
        lastName: "Photographer",
        location: "San Francisco, CA",
        serviceIDs: ["27"],
        reviewIDs: []
    },
    // Graphic Design
    {
        // _id: "65fe9a5396346912b7163306",
        clerkId: "clerkId28",
        imageUrl: "https://source.unsplash.com/woman-standing-near-white-petaled-flowers-MLOZe7YyVnY",
        contactNumber: "567-999-1234",
        email: "designer@example.com",
        website: "designerwebsite.com",
        username: "designer123",
        firstName: "Emily",
        lastName: "Designer",
        location: "New York, NY",
        serviceIDs: ["28"],
        reviewIDs: []
    },
    // Music Lessons 
    {
        // _id: "65fe9a5396346912b7163307",
        clerkId: "clerkId29",
        imageUrl: "https://source.unsplash.com/man-in-black-hoodie-wearing-black-framed-eyeglasses-3JmfENcL24M",
        contactNumber: "678-944-2345",
        email: "musician@example.com",
        website: "musicianwebsite.com",
        username: "musiclover456",
        firstName: "Alex",
        lastName: "Musician",
        location: "Los Angeles, CA",
        serviceIDs: ["29"],
        reviewIDs: []
    },

    // Logistic
    // Moving Services
    {
        // _id: "65fe9a5396346912b7163308",
        clerkId: "clerkId30",
        imageUrl: "https://source.unsplash.com/smiling-man-stands-behind-delivery-truck-t0Aio60jD4Q",
        contactNumber: "789-012-1111",
        email: "movingcompany@example.com",
        website: "movingcompanywebsite.com",
        username: "mover123",
        firstName: "Mike",
        lastName: "Mover",
        location: "Chicago, IL",
        serviceIDs: ["30"],
        reviewIDs: []
    },
    // Courier Services
    {
        // _id: "65fe9a5396346912b7163309",
        clerkId: "clerkId31",
        imageUrl: "https://source.unsplash.com/youve-got-mail-printed-pack-BPxkU4uPq6Y",
        contactNumber: "890-123-4562",
        email: "courierservice@example.com",
        website: "courierservicewebsite.com",
        username: "courier456",
        firstName: "Emma",
        lastName: "Courier",
        location: "Houston, TX",
        serviceIDs: ["31"],
        reviewIDs: []
    },
    // Equipment Rental
    {
        // _id: "65fe9a5396346912b7163310",
        clerkId: "clerkId32",
        imageUrl: "https://source.unsplash.com/equipment-rental",
        contactNumber: "902-234-5678",
        email: "rentalservice@example.com",
        website: "rentalservicewebsite.com",
        username: "rental789",
        firstName: "Oliver",
        lastName: "Rental",
        location: "Phoenix, AZ",
        serviceIDs: ["32"],
        reviewIDs: []
    },
    // Driver Services
    {
        // _id: "65fe9a5396346912b7163313",
        clerkId: "clerkId33",
        imageUrl: "https://source.unsplash.com/man-using-smartphone-eiDw0oX8YQQ",
        contactNumber: "456-123-0123",
        email: "driver@example.com",
        website: "driverservice.com",
        username: "driverpro",
        firstName: "Emma",
        lastName: "Driver",
        location: "Miami, FL",
        serviceIDs: ["33"],
        reviewIDs: []
    },
    // Catering Service
    {
        // _id: "65fe9a5396346912b7163319",
        clerkId: "clerkId34",
        imageUrl: "https://source.unsplash.com/cooked-food-on-stainless-steel-tray-7a--Ad6mkNE",
        contactNumber: "912-345-6789",
        email: "cateringservice@example.com",
        website: "cateringserviceprovider.com",
        username: "caterchef",
        firstName: "Liam",
        lastName: "Cater",
        location: "Houston, TX",
        serviceIDs: ["34"],
        reviewIDs: []
    },
    // Pet Sitting Service
    {
        // _id: "65fe9a5396346912b7163320",
        clerkId: "clerkId35",
        imageUrl: "https://source.unsplash.com/toddler-hugging-siberian-husky-N_INAlQoO6Y",
        contactNumber: "923-456-7890",
        email: "petsitter@example.com",
        website: "petsittingserviceprovider.com",
        username: "petcarepro",
        firstName: "Emma",
        lastName: "PetCare",
        location: "Chicago, IL",
        serviceIDs: ["35"],
        reviewIDs: []
    },

    // Collab
    // Application Development
    {
        // _id: "65fe9a5396346912b7163328",
        clerkId: "clerkId36",
        imageUrl: "https://source.unsplash.com/person-sitting-on-gaming-chair-while-playing-video-game-Mf23RF8xArY",
        contactNumber: "123-456-7890",
        email: "john@example.com",
        website: "example.com",
        username: "johnappdev",
        firstName: "John",
        lastName: "Doe",
        location: "New York, NY",
        serviceIDs: ["36"],
        reviewIDs: []
    },
    // Cake Baking Workshop
    {
        // _id: "65fe9a5396346912b7163329",
        clerkId: "clerkId37",
        imageUrl: "https://source.unsplash.com/a-person-kneading-dough-on-top-of-a-counter-zTG8dSz10tQ",
        contactNumber: "987-654-3210",
        email: "jane@example.com",
        website: "example.com",
        username: "janebaker",
        firstName: "Jane",
        lastName: "Smith",
        location: "Los Angeles, CA",
        serviceIDs: ["37"],
        reviewIDs: []
    },
    // Data Science Bootcamp
    {
        // _id: "65fe9a5396346912b7163327",
        clerkId: "clerkId38",
        imageUrl: "https://source.unsplash.com/three-men-sitting-on-chair-beside-tables-mpN7xjKQ_Ns",
        contactNumber: "456-333-0123",
        email: "noah@example.com",
        website: "example.com",
        username: "noahdatascience",
        firstName: "Noah",
        lastName: "Johnson",
        location: "San Francisco, CA",
        serviceIDs: ["38"],
        reviewIDs: []
    },
    // Photography Workshop
    {
        // _id: "65fe9a5396346912b7163326",
        clerkId: "clerkId39",
        imageUrl: "https://source.unsplash.com/person-taking-photo-using-canon-camera-in-shallow-focus-lens-jkZs3Oi9pq0",
        contactNumber: "789-012-2222",
        email: "mike@example.com",
        website: "example.com",
        username: "mikephotography",
        firstName: "Mike",
        lastName: "Williams",
        location: "Chicago, IL",
        serviceIDs: ["39"],
        reviewIDs: []
    },
    // Web Development Bootcamp
    {
        // _id: "65fe9a5396346912b7163325",
        clerkId: "clerkId40",
        imageUrl: "https://source.unsplash.com/three-person-sitting-in-front-of-table-with-laptop-computers-RDYdOvk8ats",
        contactNumber: "321-654-9870",
        email: "sara@example.com",
        website: "example.com",
        username: "sarawebdev",
        firstName: "Sara",
        lastName: "Brown",
        location: "Austin, TX",
        serviceIDs: ["40"],
        reviewIDs: []
    },
    // Graphic Design Workshop
    {
        // _id: "65fe9a5396346912b7163324",
        clerkId: "clerkId41",
        imageUrl: "https://source.unsplash.com/two-women-talking-while-looking-at-laptop-computer-7okkFhxrxNw",
        contactNumber: "012-345-6789",
        email: "alex@example.com",
        website: "example.com",
        username: "alexgraphic",
        firstName: "Alex",
        lastName: "Davis",
        location: "Seattle, WA",
        serviceIDs: ["41"],
        reviewIDs: []
    },

    // Health
    // General Physician
    {
        // _id: "65fe9a5396346912b716332a",
        clerkId: "clerkId42",
        imageUrl: "https://source.unsplash.com/man-sitting-on-grey-sofa-dJzJkNdp9wc",
        contactNumber: "126-456-7890",
        email: "john2@example.com",
        website: "https://www.example.com/john",
        username: "john",
        firstName: "John",
        lastName: "Doe",
        location: "Anycity, USA",
        serviceIDs: ["42"],
        reviewIDs: []
    },
    // Dentist
    {
        // _id: "65fe9a5396346912b716332b",
        clerkId: "clerkId43",
        imageUrl: "https://source.unsplash.com/woman-with-silver-and-yellow-hoop-earrings-8BkF0sTC6Uo",
        contactNumber: "456-999-0123",
        email: "emma@example.com",
        website: "https://www.example.com/emma",
        username: "emma",
        firstName: "Emma",
        lastName: "Smith",
        location: "Anycity, USA",
        serviceIDs: ["43"],
        reviewIDs: []
    },
    // Pediatrician
    {
        // _id: "65fe9a5396346912b716332c",
        clerkId: "clerkId44",
        imageUrl: "https://source.unsplash.com/a-woman-holding-a-baby-on-top-of-a-table-DjG-B1lqT90",
        contactNumber: "789-012-3333",
        email: "susan@example.com",
        website: "https://www.example.com/susan",
        username: "susan",
        firstName: "Susan",
        lastName: "Johnson",
        location: "Anycity, USA",
        serviceIDs: ["44"],
        reviewIDs: []
    },      
    // Optometrist
    {
        // _id: "65fe9a5396346912b716332d",
        clerkId: "clerkId45",
        imageUrl: "https://source.unsplash.com/a-close-up-of-a-pair-of-medical-equipment--OpWKFHA_yQ",
        contactNumber: "890-123-4367",
        email: "michael@example.com",
        website: "https://www.example.com/michael",
        username: "michael",
        firstName: "Michael",
        lastName: "Brown",
        location: "Anycity, USA",
        serviceIDs: ["45"],
        reviewIDs: []
    },
    // Dermatologist
    {
        // _id: "65fe9a5396346912b716332e",
        clerkId: "clerkId46",
        imageUrl: "https://source.unsplash.com/woman-doing-liposuction-on-her-face-PqyzuzFiQfY",
        contactNumber: "903-234-5678",
        email: "olivia@example.com",
        website: "https://www.example.com/olivia",
        username: "olivia",
        firstName: "Olivia",
        lastName: "Wilson",
        location: "Anycity, USA",
        serviceIDs: ["46"],
        reviewIDs: []
    },
    // Chiropractor
    {
        // _id: "65fe9a5396346912b716332f",
        clerkId: "clerkId47",
        imageUrl: "https://source.unsplash.com/mans-face-KVIlNRoGwxk",
        contactNumber: "212-345-6789",
        email: "david@example.com",
        website: "https://www.example.com/david",
        username: "david",
        firstName: "David",
        lastName: "Jones",
        location: "Anycity, USA",
        serviceIDs: ["47"],
        reviewIDs: []
    },

    // Tutor
    // Guitar Tutor
    {
        // _id: "65fe9a5396346912b7163251",
        clerkId: "clerkId48",
        imageUrl: "https://source.unsplash.com/building-beside-body-of-water-during-golden-hour-aNoP6f4P_nY",
        contactNumber: "587-587-5877",
        email: "chrisdojacob@gmail.com",
        website: "chrisd.com",
        username: "chrisdojacob",
        firstName: "Chris do",
        lastName: "Jake",
        location: "Calgary, AB",
        serviceIDs: ["48"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // Cooking Classes
    {
        // _id: "65fe9a5396346912b7163254",
        clerkId: "clerkId49",
        imageUrl: "https://source.unsplash.com/woman-in-black-long-sleeve-shirt-carrying-girl-in-pink-jacket-tHLCjhDCw3M",
        contactNumber: "555-123-4567",
        email: "julia@culinarydelights.com",
        website: "culinarydelights.com",
        username: "juliacook",
        firstName: "Julia",
        lastName: "Cook",
        location: "Chicago, IL",
        serviceIDs: ["49"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // Language Tutor
    {
        // _id: "65fe9a5396346912b7163256",
        clerkId: "clerkId50",
        imageUrl: "https://source.unsplash.com/woman-in-blue-tank-top-standing-beside-white-wall-TXxiFuQLBKQ",
        contactNumber: "987-654-3910",
        email: "sophie@languagemasters.com",
        website: "languagemasters.com",
        username: "sophieling",
        firstName: "Sophie",
        lastName: "Linguist",
        location: "Seattle, WA",
        serviceIDs: ["50"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // Photography Lessons
    {
        // _id: "65fe9a5396346912b7163257",
        clerkId: "clerkId51",
        imageUrl: "https://source.unsplash.com/man-holding-up-canon-dslr-camera-jUAcCtbMb0k",
        contactNumber: "555-123-7890",
        email: "alex@shuttermasters.com",
        website: "shuttermasters.com",
        username: "alexshutter",
        firstName: "Alex",
        lastName: "Shutter",
        location: "San Francisco, CA",
        serviceIDs: ["51"],
        reviewIDs: [],
        reservationIDs: [],
    },
    // // Yoga Instructor
    {
        // _id: "65fe9a5396346912b7163258",
        clerkId: "clerkId52",
        imageUrl: "https://source.unsplash.com/woman-wearing-black-sports-bra-4gcqRf3-f2I",
        contactNumber: "789-456-1230",
        email: "emma@yogamasters.com",
        website: "yogamasters.com",
        username: "emma_yoga",
        firstName: "Emma",
        lastName: "Yoga",
        location: "Los Angeles, CA",
        serviceIDs: ["52"],
        reviewIDs: []
    },
    // Math Tutor
    {
        // _id: "65fe9a5396346912b7163259",
        clerkId: "clerkId53",
        imageUrl: "https://source.unsplash.com/mens-white-dress-shirt-standing-beside-woman-holding-white-book-close-up-photography-OfbyslkgjNg",
        contactNumber: "222-456-7890",
        email: "jason@mathgenius.com",
        website: "mathgenius.com",
        username: "jason_math",
        firstName: "Jason",
        lastName: "Math",
        location: "New York, NY",
        serviceIDs: ["53"],
        reviewIDs: []
    },

];

export default dummyUsers;
