import { ReservationItem } from "@/lib/database/models/reservation.model";

export const dummyReservations: ReservationItem[] = [
    {
        _id: "1",
        createdAt: new Date(),
        stripeId: "stripeId1",
        totalAmount: 100,
        reservationDate: new Date(),
        clientId: { _id: "1", firstName: "Enya", lastName: "Umanzor" },
        service: { 
            _id: "1", 
            title: "Wall Painter",
            image: "https://source.unsplash.com/construction-worker-plastering-gypsum-walls-inside-the-house-xlH9sV9-wd0",
            location: "24 whitecres Ave, Calgary AB",
        },
        date: "12:30 PM | 19 Febraury 2024",
        notes: "Notes1",
        status: "pending",
    },
    {
        _id: "2",
        createdAt: new Date(),
        stripeId: "stripeId2",
        totalAmount: 110,
        reservationDate: new Date(),
        clientId: { _id: "2",firstName: "Alice", lastName: "Johnson" },
        service: { 
            _id: "2", 
            title: "Electrician",
            image: "https://source.unsplash.com/man-in-brown-hat-holding-black-and-gray-power-tool-_2AlIm-F6pw",
            location: "123 Oak Street, Anytown, USA",
        },
        date: "10:00 AM | 20 February 2024",
        notes: "Notes2",
        status: "confirmed",
    },
    {
        _id: "3",
        createdAt: new Date(),
        stripeId: "stripeId3",
        totalAmount: 300,
        reservationDate: new Date(),
        clientId: { _id: "3", firstName: "Bob", lastName: "Smith" },
        service: { 
            _id: "3", 
            title: "Plumber",
            image: "https://source.unsplash.com/a-man-working-on-a-pipe-in-a-wall-c314Gh8dXAo",
            location: "456 Maple Avenue, Sometown, USA",
        },
        date: "11:30 AM | 21 February 2024",
        notes: "Notes3",
        status: "completed",
    },
    {
        _id: "4",
        createdAt: new Date(),
        stripeId: "stripeId4",
        totalAmount: 400,
        reservationDate: new Date(),
        clientId: { _id: "4", firstName: "Charlie", lastName: "Brown" },
        service: { 
            _id: "4", 
            title: "Carpenter",
            image: "https://source.unsplash.com/man-using-sander-on-beige-wooden-surface-mLO6ILUbADA",
            location: "789 Pine Lane, Anycity, USA",
        },
        date: "2:00 PM | 22 February 2024",
        notes: "Notes4",
        status: "cancelled",
    },
    {
        _id: "5",
        createdAt: new Date(),
        stripeId: "stripeId4",
        totalAmount: 400,
        reservationDate: new Date(),
        clientId: { _id: "4", firstName: "Emily", lastName: "Parker" },
        service: { 
            _id: "4", 
            title: "House Cleaning",
            image: "https://source.unsplash.com/a-woman-in-a-green-shirt-and-black-gloves-vacuuming-a-gray-ottoman-5TXz228u4eo",
            location: "",
        },
        date: "10:00 AM | 20 March 2024",
        notes: "Notes4",
        status: "cancelled",
    },
    {
        _id: "6",
        createdAt: new Date(),
        stripeId: "stripeId4",
        totalAmount: 400,
        reservationDate: new Date(),
        clientId: { _id: "4", firstName: "Daniel", lastName: "Johnson" },
        service: { 
            _id: "4", 
            title: "Gardening",
            image: "https://source.unsplash.com/man-in-white-t-shirt-and-white-pants-sitting-on-brown-wooden-bench-JCZ2pE-Szpw",
            location: "456 Oak Avenue, Anytown",
        },
        date: "11:30 AM | 21 March 2024",
        notes: "Notes4",
        status: "cancelled",
    },
    {
        _id: "7",
        createdAt: new Date(),
        stripeId: "stripeId4",
        totalAmount: 400,
        reservationDate: new Date(),
        clientId: { _id: "4", firstName: "Sophia", lastName: "Smith" },
        service: { 
            _id: "4", 
            title: "Interior Design",
            image: "https://source.unsplash.com/white-and-brown-living-room-set-9M66C_w_ToM",
            location: "789 Maple Drive, Anycity",
        },
        date: "2:00 PM | 22 March 2024",
        notes: "Notes4",
        status: "cancelled",
    },
    {
        _id: "8",
        createdAt: new Date(),
        stripeId: "stripeId4",
        totalAmount: 400,
        reservationDate: new Date(),
        clientId: { _id: "4", firstName: "Olivia", lastName: "Taylor" },
        service: { 
            _id: "4", 
            title: "Home Renovation",
            image: "https://source.unsplash.com/woman-in-white-shirt-wearing-white-helmet-vK6HbLrGzZc",
            location: "321 Pine Street, Anycity",
        },
        date: "9:00 AM | 23 March 2024",
        notes: "Notes4",
        status: "cancelled",
    },
    {
        _id: "9",
        createdAt: new Date(),
        stripeId: "stripeId4",
        totalAmount: 400,
        reservationDate: new Date(),
        clientId: { _id: "4", firstName: "Noah", lastName: "Martinez" },
        service: { 
            _id: "4", 
            title: "Roof Repair",
            image: "https://source.unsplash.com/a-man-standing-on-the-roof-of-a-house--1l0iZaM8ms",
            location: "789 Oak Lane, Springfield",
        },
        date: "10:30 AM | 24 March 2024",
        notes: "Notes4",
        status: "cancelled",
    },
    {
        _id: "10",
        createdAt: new Date(),
        stripeId: "stripeId4",
        totalAmount: 400,
        reservationDate: new Date(),
        clientId: { _id: "4", firstName: "Sophia", lastName: "Smith" },
        service: { 
            _id: "4", 
            title: "Interior Design",
            image: "https://source.unsplash.com/tufted-sofa-near-coffee-table-MNz7IGrcEl0",
            location: "789 Maple Drive, Anycity",
        },
        date: "11:30 AM | 21 March 2024",
        notes: "Notes4",
        status: "cancelled",
    },

];